[package]
name = "assert2"
description = "assert!(...) and check!(...) macros inspired by Catch2"
version = "0.3.9"
license = "BSD-2-Clause"
authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"Mara Bos <m-ou.se@m-ou.se>",
]

rust-version = "1.66"
edition = "2021"

repository = "https://github.com/de-vri-es/assert2-rs"
documentation = "https://docs.rs/assert2"
readme = "README.md"
keywords = ["assert", "check", "test", "unit-test"]
categories = ["development-tools::debugging", "development-tools::testing"]

[dependencies]
assert2-macros = { version = "=0.3.9", path = "assert2-macros" }
yansi = "0.5.0"
atty = "0.2.14"

[workspace]
resolver = "2"
members = ["assert2-macros"]
