name: CI
on:
  push: { branches: "master" }
  pull_request: { branches: "*" }

jobs:
  nightly:
    name: Build and test on nightly with all features
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --color=always
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --color=always

  stable:
    name: Build and test on stable without features
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --color=always
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --color=always
